/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//component_dev': RouteRecordInfo<'//component_dev', '/component_dev', Record<never, never>, Record<never, never>>,
    '//component_dev/': RouteRecordInfo<'//component_dev/', '/component_dev', Record<never, never>, Record<never, never>>,
    '//component_dev/button': RouteRecordInfo<'//component_dev/button', '/component_dev/button', Record<never, never>, Record<never, never>>,
    '//component_dev/echart_graph': RouteRecordInfo<'//component_dev/echart_graph', '/component_dev/echart_graph', Record<never, never>, Record<never, never>>,
    '//component_dev/editor': RouteRecordInfo<'//component_dev/editor', '/component_dev/editor', Record<never, never>, Record<never, never>>,
    '//component_dev/file_tree': RouteRecordInfo<'//component_dev/file_tree', '/component_dev/file_tree', Record<never, never>, Record<never, never>>,
    '//component_dev/screen_auto': RouteRecordInfo<'//component_dev/screen_auto', '/component_dev/screen_auto', Record<never, never>, Record<never, never>>,
    '//component_dev/screen_full': RouteRecordInfo<'//component_dev/screen_full', '/component_dev/screen_full', Record<never, never>, Record<never, never>>,
    '//component_dev/state': RouteRecordInfo<'//component_dev/state', '/component_dev/state', Record<never, never>, Record<never, never>>,
    '//component_dev/todo': RouteRecordInfo<'//component_dev/todo', '/component_dev/todo', Record<never, never>, Record<never, never>>,
    '/_dev/': RouteRecordInfo<'/_dev/', '/_dev', Record<never, never>, Record<never, never>>,
    '/_dev/libBase/element_plus_import': RouteRecordInfo<'/_dev/libBase/element_plus_import', '/_dev/libBase/element_plus_import', Record<never, never>, Record<never, never>>,
    '/_server/table/DB': RouteRecordInfo<'/_server/table/DB', '/_server/table/DB', Record<never, never>, Record<never, never>>,
    '/[..404]': RouteRecordInfo<'/[..404]', '/:04(.*)', { 04: ParamValue<true> }, { 04: ParamValue<false> }>,
    '/blog/add': RouteRecordInfo<'/blog/add', '/blog/add', Record<never, never>, Record<never, never>>,
    '/blog/instruction': RouteRecordInfo<'/blog/instruction', '/blog/instruction', Record<never, never>, Record<never, never>>,
    '/blog/read': RouteRecordInfo<'/blog/read', '/blog/read', Record<never, never>, Record<never, never>>,
  }
}
